node{

stage('SCM'){
//git clone
git 'https://github.com/GitPracticeRepo/spring-petclinic.git'
}
stage('build the package'){
//mvn package
sh  'mvn package'
}
stage('archival'){
//archiving artifacts
archive 'target/*.jar'
}
stage('archival'){
//archiving artifacts
archive 'target/*.jar'
}
stage('archival'){
//archiving artifacts
junit 'target/surefire-reports/*.xml'
}
}