node{

stage('SCM'){
//git clone
git 'https://github.com/Srinu7358/JenkinsPipeline1.git'
}
stage('build the package'){
//mvn package
sh  'mvn package'
}
stage('archival'){
//archiving artifacts
archive 'target/*.jar'
}

}